[platformio]
default_envs = frdm_kl25z

[env:frdm_kl25z]
platform = freescalekinetis
framework = zephyr
board = frdm_kl25z
debug_tool = custom
build_type = release
build_src_filter = +<main.c>
build_flags =
    -DAPP_USA_FIR=0
    -DAPP_TEMPO_ETAPA_S=15
platform_packages =
    platformio/framework-zephyr@~3.40200.0
; Use apenas para depurar com OpenOCD. Build debug fica grande demais para
; os 128 KB de flash da FRDM-KL25Z.
debug_build_flags = -O0 -g -ggdb
debug_server =
    openocd
    -f lib\Debug\interface.cfg
    -f target/kl25.cfg

[env:frdm_kl25z_fir]
extends = env:frdm_kl25z
build_flags =
    -DAPP_USA_FIR=1
    -DAPP_TEMPO_ETAPA_S=15
